# Generated by Django 3.0.14 on 2022-03-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=122)),
                ('Lastname', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('Username', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
