# Generated by Django 3.0.14 on 2022-03-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vimalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
